export const DIRECOES = {
  a: {
    id: "a" as const,
    nome: "Direção A",
    subnome: "Petróleo & Marfim",
    fundo: "#22221F",
    texto: "#F3EFE6",
    ancora: "#33505B",
    apoio: "#C9B8A0",
    fontTitulo: "var(--font-fraunces)",
    fontTexto: "var(--font-inter)",
    fontTituloNome: "Fraunces",
    fontTextoNome: "Inter",
    tom: "Estratégico, sóbrio — remete a navegação e copiloto.",
  },
  b: {
    id: "b" as const,
    nome: "Direção B",
    subnome: "Grafite & Terracota Fosca",
    fundo: "#221F1D",
    texto: "#EDE7DD",
    ancora: "#A9694F",
    apoio: "#7C8B7A",
    fontTitulo: "var(--font-newsreader)",
    fontTexto: "var(--font-public-sans)",
    fontTituloNome: "Newsreader",
    fontTextoNome: "Public Sans",
    tom: "Mais humano e orgânico — conecta com sustentabilidade aplicada.",
  },
  c: {
    id: "c" as const,
    nome: "Direção C",
    subnome: "Ardósia & Gelo",
    fundo: "#23282B",
    texto: "#F4F6F5",
    ancora: "#4C6B72",
    apoio: "#8FA39C",
    fontTitulo: "var(--font-fraunces)",
    fontTexto: "var(--font-inter)",
    fontTituloNome: "Fraunces",
    fontTextoNome: "Inter",
    tom: "Frio e técnico, mas nunca duro — precisão sem parecer corporativo padrão.",
  },
  d: {
    id: "d" as const,
    nome: "Direção D",
    subnome: "Índigo & Neve",
    fundo: "#1E1B2A",
    texto: "#F7F7F9",
    ancora: "#4A5FE0",
    apoio: "#A79FC4",
    fontTitulo: "var(--font-newsreader)",
    fontTexto: "var(--font-public-sans)",
    fontTituloNome: "Newsreader",
    fontTextoNome: "Public Sans",
    tom: "Um único azul de destaque, não vários — clareza em vez de excesso.",
  },
};

export type DirecaoId = keyof typeof DIRECOES;
